export type SignalBar = { date: string; open: number; high: number; low: number; close: number; volume: number };
export type CoreSignal = { asOf: string; close: number; track: 'TRACK_1' | 'TRACK_2'; action: 'PARTIAL_SELL' | 'PARTIAL_BUY' | 'HOLD'; percentage: number; sellPercentage: number; buyPercentage: number; signals: { group: string; name: string; weight: number }[] };

const sma = (v: number[], n: number) => v.map((_, i) => i >= n - 1 ? v.slice(i - n + 1, i + 1).reduce((a, b) => a + b, 0) / n : null) as (number | null)[];
const ema = (v: number[], n: number) => { const r = Array<number | null>(v.length).fill(null); if (v.length < n) return r; let p = v.slice(0, n).reduce((a, b) => a + b, 0) / n; r[n - 1] = p; const k = 2 / (n + 1); for (let i = n; i < v.length; i++) { p = (v[i] - p) * k + p; r[i] = p; } return r; };
const mid = (h: number[], l: number[], n: number) => h.map((_, i) => i >= n - 1 ? (Math.max(...h.slice(i - n + 1, i + 1)) + Math.min(...l.slice(i - n + 1, i + 1))) / 2 : null) as (number | null)[];
const cross = (a: (number | null)[], b: (number | null)[], up: boolean) => { const i = a.length - 1; return i > 0 && [a[i - 1], b[i - 1], a[i], b[i]].every((x) => x !== null) && (up ? a[i - 1]! <= b[i - 1]! && a[i]! > b[i]! : a[i - 1]! >= b[i - 1]! && a[i]! < b[i]!); };
const percentile = (v: (number | null)[], p: number) => { const a = v.filter((x): x is number => x !== null).sort((x, y) => x - y); if (!a.length) return null; const x = (a.length - 1) * p, lo = Math.floor(x), hi = Math.min(lo + 1, a.length - 1); return a[lo] + (a[hi] - a[lo]) * (x - lo); };
const regression = (v: number[]) => { const n = v.length, xm = (n - 1) / 2, ym = v.reduce((a, b) => a + b, 0) / n, den = v.reduce((s, _, i) => s + (i - xm) ** 2, 0); const slope = v.reduce((s, y, i) => s + (i - xm) * (y - ym), 0) / den; return { slope, at: (i: number) => ym - slope * xm + slope * i }; };
const dmi = (h: number[], l: number[], c: number[]) => { const up = Array(c.length).fill(0), down = Array(c.length).fill(0), tr = Array(c.length).fill(0); for (let i = 1; i < c.length; i++) { const u = h[i] - h[i - 1], d = l[i - 1] - l[i]; up[i] = u > d && u > 0 ? u : 0; down[i] = d > u && d > 0 ? d : 0; tr[i] = Math.max(h[i] - l[i], Math.abs(h[i] - c[i - 1]), Math.abs(l[i] - c[i - 1])); } const ts = sma(tr, 14), ps = sma(up, 14), ms = sma(down, 14); return [ps.map((x, i) => ts[i] ? 100 * x! / ts[i]! : null), ms.map((x, i) => ts[i] ? 100 * x! / ts[i]! : null)] as [(number | null)[], (number | null)[]]; };
const obv = (c: number[], v: number[]) => c.map((_, i) => i ? (c[i] > c[i - 1] ? v[i] : c[i] < c[i - 1] ? -v[i] : 0) : 0).reduce<number[]>((r, x, i) => { r.push((r[i - 1] ?? 0) + x); return r; }, []);
const sig = (group: string, name: string, weight: number) => ({ group, name, weight });

export function analyzeCoreSignal(history: SignalBar[]): CoreSignal {
  const clean = history.filter((x) => [x.open, x.high, x.low, x.close, x.volume].every(Number.isFinite));
  if (clean.length < 120) throw new Error('신호 계산에는 최소 120거래일의 일봉 데이터가 필요합니다.');
  const o = clean.map((x) => x.open), h = clean.map((x) => x.high), l = clean.map((x) => x.low), c = clean.map((x) => x.close), v = clean.map((x) => x.volume);
  const ma5 = sma(c, 5), ma10 = sma(c, 10), ma20 = sma(c, 20), ma60 = sma(c, 60), e12 = ema(c, 12), e26 = ema(c, 26);
  const macd = c.map((_, i) => e12[i] !== null && e26[i] !== null ? e12[i]! - e26[i]! : null), compact = ema(macd.filter((x): x is number => x !== null), 9), macdSignal = macd.map((x, i) => x === null ? null : compact[macd.slice(0, i + 1).filter((y): y is number => y !== null).length - 1]);
  const tenkan = mid(h, l, 9), kijun = mid(h, l, 26), spanBase = mid(h, l, 52), spanA = Array<number | null>(c.length).fill(null), spanB = Array<number | null>(c.length).fill(null);
  for (let i = 0; i < c.length - 26; i++) { if (tenkan[i] !== null && kijun[i] !== null) spanA[i + 26] = (tenkan[i]! + kijun[i]!) / 2; if (spanBase[i] !== null) spanB[i + 26] = spanBase[i]; }
  const [plus, minus] = dmi(h, l, c), ob = obv(c, v), obMa = sma(ob, 20), distance = c.map((x, i) => ma5[i] ? x / ma5[i]! * 100 : null), p90 = percentile(distance.slice(Math.max(0, distance.length - 501), -1), .9), p10 = percentile(distance.slice(Math.max(0, distance.length - 501), -1), .1);
  const track = ma60.at(-1) !== null && spanB.at(-1) !== null && c.at(-1)! > ma60.at(-1)! && c.at(-1)! > spanB.at(-1)! ? 'TRACK_1' : 'TRACK_2';
  const sells: { group: string; name: string; weight: number }[] = [], buys: typeof sells = [];
  if (cross(macd, macdSignal, false)) sells.push(sig('A', 'MACD 시그널선 하향 돌파', 5)); if (cross(macd, macdSignal, true)) buys.push(sig("A'", 'MACD 시그널선 상향 돌파', 5));
  if (cross(c.map(Number), tenkan, false)) sells.push(sig('A', '종가 일목 전환선 하향 이탈', 5)); if (cross(c.map(Number), tenkan, true)) buys.push(sig("A'", '종가 일목 전환선 상향 돌파', 5));
  const bS: string[] = [], bB: string[] = []; if (cross(c.map(Number), ma5, false)) bS.push('5일선 하향 이탈'); if (cross(c.map(Number), ma5, true)) bB.push('5일선 상향 돌파'); if (ma5.at(-3) !== null && ma5.at(-2)! >= ma5.at(-3)! && ma5.at(-1)! < ma5.at(-2)!) bS.push('5일선 기울기 음전환'); if (ma5.at(-3) !== null && ma5.at(-2)! <= ma5.at(-3)! && ma5.at(-1)! > ma5.at(-2)!) bB.push('5일선 기울기 양전환'); if (cross(ma5, ma10, false)) bS.push('5/10 데드크로스'); if (cross(ma5, ma10, true)) bB.push('5/10 골든크로스'); if (cross(tenkan, kijun, false)) bS.push('일목 전환선/기준선 데드크로스'); if (cross(tenkan, kijun, true)) bB.push('일목 전환선/기준선 골든크로스'); if (bS.length) sells.push(sig('B', bS.join(' / '), 10)); if (bB.length) buys.push(sig("B'", bB.join(' / '), 10));
  const cS: string[] = [], cB: string[] = []; if (cross(ma5, ma20, false)) cS.push('5/20 데드크로스'); if (cross(ma5, ma20, true)) cB.push('5/20 골든크로스'); if (cross(ma20, ma60, false)) cS.push('20/60 데드크로스'); if (cross(ma20, ma60, true)) cB.push('20/60 골든크로스'); if (ma20.at(-2)! >= ma20.at(-3)! && ma20.at(-1)! < ma20.at(-2)!) cS.push('20일선 기울기 음전환'); if (ma20.at(-2)! <= ma20.at(-3)! && ma20.at(-1)! > ma20.at(-2)!) cB.push('20일선 기울기 양전환'); if (kijun.at(-1)! < kijun.at(-2)! && kijun.at(-2)! < kijun.at(-3)! && kijun.at(-3)! < kijun.at(-4)!) cS.push('일목 기준선 3일 연속 하락'); if (kijun.at(-1)! > kijun.at(-2)! && kijun.at(-2)! > kijun.at(-3)! && kijun.at(-3)! > kijun.at(-4)!) cB.push('일목 기준선 3일 연속 상승'); if (cS.length) sells.push(sig('C', cS.join(' / '), 15)); if (cB.length) buys.push(sig("C'", cB.join(' / '), 15));
  const vr = v.at(-1)! / (v.slice(-6, -1).reduce((a, b) => a + b, 0) / 5 || 1), ret = (c.at(-1)! / c.at(-2)! - 1) * 100, neg = vr >= 1.3 && c.at(-1)! < o.at(-1)! && ret <= -1.5, pos = vr >= (track === 'TRACK_2' ? 2 : 1.3) && c.at(-1)! > o.at(-1)! && ret >= 1.5;
  if (c.length >= 63) { const low = regression(l.slice(-62, -2)), high = regression(h.slice(-62, -2)), support = Math.min(...l.slice(-62, -2)); if (low.slope > 0 && c.at(-2)! >= low.at(60) && c.at(-1)! < low.at(61) && neg) sells.push(sig('D', '상승 추세선 하향 이탈(거래량 확인)', 15)); if (c.at(-2)! >= support && c.at(-1)! < support && neg) sells.push(sig('D', '최근 60일 지지선 붕괴(거래량 확인)', 15)); let breakout = high.slope < 0 && c.at(-2)! <= high.at(60) && c.at(-1)! > high.at(61); if (track === 'TRACK_2') { const confirmed = regression(h.slice(-63, -3)); breakout = confirmed.slope < 0 && c.at(-3)! > confirmed.at(60) && c.at(-2)! > confirmed.at(61) && c.at(-1)! > confirmed.at(62); } if (breakout && pos) buys.push(sig("D'", '하락 추세선 상향 돌파(거래량 확인)', 15)); let bounce = l.at(-1)! <= support * 1.01 && c.at(-1)! > support && pos; if (track === 'TRACK_2') bounce = c.at(-3)! > support && c.at(-2)! > support && c.at(-1)! > support && l.at(-3)! <= support * 1.01 && pos; if (bounce) buys.push(sig("D'", '최근 60일 지지선 반등(거래량 확인)', 15)); }
  for (const [line, sn, bn] of [[kijun, '기준선 아래 진입', '기준선 위 복귀'], [spanA, '선행스팬1 아래 진입', '선행스팬1 위 복귀'], [spanB, '선행스팬2 아래 이탈', '선행스팬2 위 돌파']] as const) { if (cross(c.map(Number), line, false)) sells.push(sig('E', sn, 5)); if (cross(c.map(Number), line, true)) buys.push(sig("E'", bn, 5)); }
  if (c.length >= 28) { if (c.at(-2)! >= c.at(-28)! && c.at(-1)! < c.at(-27)!) sells.push(sig('E', '후행스팬 역전', 5)); if (c.at(-2)! <= c.at(-28)! && c.at(-1)! > c.at(-27)!) buys.push(sig("E'", '후행스팬 양전환', 5)); }
  if (p90 !== null && distance.at(-2)! <= p90 && distance.at(-1)! > p90) sells.push(sig('F', '이격도 최근 2년 상위 10% 진입', 5)); if (p10 !== null && distance.at(-2)! < p10 && distance.at(-1)! >= p10) buys.push(sig("F'", '이격도 최근 2년 하위 10% 탈출', 5)); if (cross(minus, plus, true)) sells.push(sig('F', 'DI-가 DI+ 상향 돌파', 5)); if (cross(plus, minus, true)) buys.push(sig("F'", 'DI+가 DI- 상향 돌파', 5)); if (obMa.at(-1) !== null && ob.at(-1)! < obMa.at(-1)! && ob.at(-2)! < obMa.at(-2)! && ob.at(-3)! < obMa.at(-3)! && ob.at(-4)! >= obMa.at(-4)!) sells.push(sig('F', 'OBV 20일선 하향 이탈 3일 지속', 5)); if (cross(ob, obMa, true)) buys.push(sig("F'", 'OBV 20일선 상승 전환', 5));
  const sellPercentage = Math.min(100, sells.reduce((s, x) => s + x.weight, 0)), rawBuy = Math.min(100, buys.reduce((s, x) => s + x.weight, 0)), buyPercentage = rawBuy * (track === 'TRACK_2' ? .5 : 1), action = sellPercentage > buyPercentage ? 'PARTIAL_SELL' : buyPercentage > sellPercentage ? 'PARTIAL_BUY' : 'HOLD', percentage = action === 'PARTIAL_SELL' ? sellPercentage : action === 'PARTIAL_BUY' ? buyPercentage : 0;
  return { asOf: clean.at(-1)!.date, close: c.at(-1)!, track, action, percentage: Math.round(percentage * 10) / 10, sellPercentage, buyPercentage, signals: action === 'PARTIAL_SELL' ? sells : action === 'PARTIAL_BUY' ? buys : [] };
}
